#!/bin/bash
sudo yum install wget curl deltarpm -y
sudo yum check-update
curl -fsSL https://get.docker.com/ | sh
sudo systemctl start docker
sudo systemctl enable docker
sudo systemctl status docker
sudo usermod -aG docker $(whoami)
sudo usermod -aG docker $USER
